global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # OTEL Collector — метрики отправленные приложением через OTLP
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']

  # Приложение напрямую — Prometheus exporter на debug порту
  - job_name: 'template'
    static_configs:
      - targets: ['host.docker.internal:7003']
    metrics_path: '/metrics'
    scrape_interval: 5s
