apiVersion: 1

datasources:
  - name: "Prometheus"
    type: prometheus
    access: proxy
    orgId: 1
    isDefault: true
    url: http://prometheus:9090
    uid: prometheus
    jsonData:
      prometheusType: Prometheus
      exemplarTraceIdDestinations:
        - datasourceUid: tempo
          name: trace_id

  - name: "Tempo"
    type: tempo
    access: proxy
    orgId: 1
    url: http://tempo:3200
    uid: tempo
    jsonData:
      httpMethod: GET
      grpcAddress: tempo:9096
      nodeGraph:
        enabled: false
      serviceMap:
        datasourceUid: ""
      search:
        hide: false
