# Константные значения общие для всех окружений
app:
  name: "template"
  version: "1.0.0"

server:
  host: "localhost"
  port: "7001"
  env: "local"
  http_port: "7001"
  grpc_port: "7000"
  debug_port: "7003"
  swagger_port: "7002"
  auth_bypass: true
  csrf_key: "32-byte-long-auth-key-for-local-dev"

log:
  level: "DEBUG"
  format: false
  loki_enabled: true
  loki_url: "http://localhost:3100/loki/api/v1/push"

metrics:
  enable_metrics: true

PG:
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "password"
  scheme: "public"
  db: "template"

rabbit:
  amqp_url: "amqp://guest:guest@localhost:5672"

JWT:
  sign_key: "secret"
  token_ttl: "20000m"
  refresh_token_ttl: "20000m"

otel:
  endpoint: "localhost:4317"
  sample_rate: 1.0

etcd:
  endpoints: "localhost:2379"
  prefix: "/flags/"

temporal:
  host: "localhost"
  port: 7233
  namespace: "default"
  task_queue: "default-task-queue"
